### PR TITLE
add `table_data_list_response` module

### PR DESCRIPTION
**Pull request by enricozb**
Fixes compilation error introduced in https://github.com/lquerel/gcp-bigquery-client/pull/67

### CODE REVIEW

**Comment by enricozb** [comment]
Are the tests flaky at all?

**Comment by lquerel** [comment]
Thank you! Version 0.18.0 published on crates.io.
Note: unit tests run ok.
